### ISSUE TITLE
`kamp edit` opens an extra buffer when only one file is provided

### ISSUE THREAD

**Issue by jtrv** [vbauerster/kampliment#5]
When using `kamp edit` with a single argument, a secondary empty buffer is opened.
i.e. `kamp edit tmp/index.html`
![image](https://user-images.githubusercontent.com/46337843/161157601-60d16613-06cd-49e5-947c-0a57ac32e25c.png)
the empty buffer does not seem to appear if I pass in more files
i.e. `kamp edit tmp/index.html tmp/index.js`
![image](https://user-images.githubusercontent.com/46337843/161157517-e00997fc-11be-4483-8dd2-3bc4efbc622b.png)
If I remove kampliment from my configuration this behavior does not persist so I am assuming this is an issue with kampliment.

**Comment by vbauerster** [comment]
I don't observe any second buffer with single param to edit. Pls update to head if you didn't.
Edit expects single file argument with optional coordinates. I actually went from multiple files to a single one on purpose.
It is because of coordinates: it could be either `file +line:col` or `+line:col file`. With multiple files it is ambiguous to parse coordinates. Do you really need it to accept multiple files?

**Comment by vbauerster** [comment]
Can you please check latest master version?

**Comment by jtrv** [comment]
Testing with the latest master and I'm not seeing the issue anymore, closing this issue.
